[package]
name = "unixConnectionConfigurator"
version = "0.1.0"
authors = ["Baj Ivan <ivanli@dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
structopt = "0.3.13"
cmd_lib = "0.7.8"
